services:
  # --------------------
  # 1. The FastAPI Backend (as a Docker container)
  # --------------------
  - type: web
    name: statement-extractor-backend
    plan: free # Note: Docker builds on the free tier can be slow.
    
    # Tell Render to use Docker and where to find the Dockerfile
    image:
      dockerfilePath: ./backend/Dockerfile # Path from the root
    
    # Health check path (optional, but good)
    healthCheckPath: /
    
    # Environment variables
    envVars:
      - key: GOOGLE_API_KEY
        fromSecret: true
      - key: PORT # Render sets this, Uvicorn will use it
        value: 8000

  # --------------------
  # 2. The Static Frontend (no change)
  # --------------------
  - type: static
    name: statement-extractor-frontend
    rootDir: frontend
    plan: free
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html